# Generated by Django 4.1 on 2022-08-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='default', verbose_name='caca'),
            preserve_default=False,
        ),
    ]
